### ISSUE TITLE
Ask the brief steps on pixel-wise labeling prediction

### ISSUE THREAD

**Issue by amiltonwong** [torrvision/crfasrnn#1]
Hi, Sadeep Jayasumana,

I had already installed crfasrnn.
As given the trained model (TVG_CRFRNN_COCO_VOC.caffemodel) , how could I perform pixel-wise labeling prediction on test image? Could you list the brief steps?

Thanks in advance!
Milton

**Comment by sadeepj** [comment]
Hi Milton,

You could use the MATLAB script https://github.com/torrvision/crfasrnn/blob/master/matlab-scripts/crfrnn_demo.m. If you have successfully run the commands "make" and "make matcaffe" as per the instructions in https://github.com/torrvision/crfasrnn/blob/master/README.md, the above MATLAB script should work OOTB.

BTW, I have just made some modifications to the above MATLAB script. So please update your code before running it.

Regards,
Sadeep

**Comment by amiltonwong** [comment]
Thanks Sadeep,

I found it and it works well (I test on MATLAB) and get the result in output.png. My further question is :
How could I append the pixel-wise labeling result (as a mask) to the original input image which is similar to the demo result image (https://github.com/torrvision/crfasrnn/blob/master/sample.png)?

Thanks in advance!

Milton

**Comment by bittnt** [comment]
@amiltonwong This question is out of the scope of this code. 

But you can change the alpha chanel of the pixel-wise labelling mask and then compose it with the original input image.

**Comment by amiltonwong** [comment]
Thanks @bittnt ,
I implement that by changing the 'AlphaData' property of image handle.
Another question: According to the updated message: https://goo.gl/6Y4j51 , after downloading the listing file "seg12valid.txt" for reduced validation set, how can I implement the evaluation (to obtain 73.0 mean-IOU score) ? Could you list the brief steps or point me to the reference places (such as VOCdevkit/VOCcode)?

Thanks in advance !
Milton

**Comment by bittnt** [comment]
@amiltonwong replace val.txt in VOCdevkit with seg12valid.txt ,or change the name. Check their toolkit:  http://host.robots.ox.ac.uk:8080/pascal/VOC/voc2012/index.html#devkit
