### ISSUE TITLE
Memory issue 

### ISSUE THREAD

**Issue by AlexTS1980** [torrvision/crfasrnn#102]
When running a 1280x720 image through crf-rnn I get the annoying message

`syncedmem.cpp:58] Check failed: error == cudaSuccess (2 vs. 0)  out of memory`

This line does some check: `CUDA_CHECK(cudaMalloc(&gpu_ptr_, size_));`

I have 64Gb RAM and run Tesla K40 with 12 Gb memory, while `Memory required for data: 3703865856`

Do I need to change some parameters (`size_`) somewhere to allow use of more memory?

**Comment by bittnt** [comment]
Probably you should resize images or crop images.

**Comment by AlexTS1980** [comment]
Thanks, I got so much. My question is whether it is possible to process an image of this size. Given the features of the machine, I don't see why not. Maybe I should tweak some setting in the source file to raise the max memory or something like this? 1

**Comment by AlexTS1980** [comment]
It's quite annoying, when I fine-tune CRFasRNN with my own data (1 extra layer + new output layer) and even with the batch size of 1 I get the same error message. Inference with 1 image (1000x600) takes 10sec on  Tesla K40. Any suggestions? Obviously I can't reduce the batch size. On CPU 20 iterations take about 30 min. Thanks.

**Comment by sadeepj** [comment]
Hi AlexTS1980,

This must be due to the K40 running out of the physical memory. To verify this, you can use nvidia-smi or any other monitoring tool to monitor the memory usage on the K40 while running the Caffe code.

I don't think you can easily fix this from software side (not unless you spend some significant amount of time optimizing the Caffe code for memory).

**Comment by AlexTS1980** [comment]
Yeah I got  it already. If, for example, I know how much memory 2x3x500x500 batch requires (say 9 GB), do you think it is possible to predict the amount of memory 2x3x720x1280 will need? We are discussing buying more powerful cards at the uni, but I'm not sure even Tesla K80 or P40 with 24 GB would be able to handle such large images. You have any ideas?

**Comment by sadeepj** [comment]
My rough estimate would be: 9 GB x (720 x 1280) / (500 x 500) ~= 33 GB. But even this is a very optimistic estimate (it assumes linear growth). So I think pretty much the only option you have is to use crops or resized images. I don't think using 500 x 500 crops will significantly affect the results.

**Comment by AlexTS1980** [comment]
Thanks @sadeepj. You may well be right about the memory. The thing is, crf-rnn and fcn produce a far better prediction for image of size 1280x720 than 500x500. I guess I'll have to live with that. Why is it the case that so much memory is needed? I mean, if 1 pixel is 86 bytes, 1 image 1280x720x3x86 ~ 23.7Mb. 100 images would be 2.3 Gb. How come in reality it takes way than that?

**Comment by AlexTS1980** [comment]
Also, in the training fcn processes 1280x720 images very fast, like 0.65s/image. It's only in the training that there's a problem with memory. Something to do with backprop?
