### ISSUE TITLE
Fail the test_multi_stage_meanfield_layer

### ISSUE THREAD

**Issue by wk910930** [torrvision/crfasrnn#103]
Dear @bittnt ,

Did you `make runtest` on latest Caffe with CPU/GPU [CRF-RNN](test_multi_stage_meanfield_layer)? I failed the test_multi_stage_meanfield_layer, while the old version seems okay.

Thanks.
Kun

**Comment by nathanin** [comment]
Hi Kun,
I also fail runtest at the meanfield_layer. I have the custom layers merged with another layer, but the rest is close to the recent crfasrnn branch. 

Additionally I find it takes a very long time to run the test in the first place.

Have you had success without the test passing? Or is there cause for concern..

**Comment by wk910930** [comment]
Dear @nathanin ,

Sorry for the late reply. Actually I found somehow in the latest Caffe with CPU/GPU CRF-RNN ([here](https://github.com/torrvision/caffe/blob/crfrnn/src/caffe/layers/meanfield_iteration.cpp#L235)), the last augment in `spatial_lattice_->compute_cpu()` is changed to `true` from `false`, which causes the error when `make runtest`. When you use `false`, everything runs okay.

I have merged the CRF-RNN module to [SSD](https://github.com/weiliu89/caffe/tree/ssd) project for my own research in [this branch](https://github.com/wk910930/caffe/tree/ssd-wk). Much modification (e.g. fix lint error, consistent with new Caffe fission, clean code) has been made for better use. You are welcome to view it.

Best regards,
Kun
