### ISSUE TITLE
What if output score map does not match the size of input image?

### ISSUE THREAD

**Issue by wk910930** [torrvision/crfasrnn#104]
Dear @bittnt ,

Usually the output score map should have the same spatial size as the input image during mean field approximation. But in my case the score map is up/down-scaled from the original spatial size. In multi_stage_meanfield_layer.cpp, will it handle such situation by sampling values from bilateral kernel and spatial kernel accordingly? 

Thanks!
Kun

**Comment by sadeepj** [comment]
Hi Kun,

The MultiStageMeanfieldLayer does not automatically handle such cases. It assumes that the image (bottom[2] in [here](https://github.com/torrvision/caffe/blob/master/src/caffe/layers/multi_stage_meanfield.cpp#L167)) and the heat-maps (bottom[0] in the above link) are of the same spatial size. You'd have to manually resize (e.g. using a different Caffe layer) either the image or the heat-maps to make them same size.
