### ISSUE TITLE
Hi ,how can segment objects in output semantic image?

### ISSUE THREAD

**Issue by huihuangz** [torrvision/crfasrnn#108]
Hi , i can not install the crfasrnn into my computer , i just want to segment the object by using project website http://crfasrnn.torr.vision.
i got a semantic image by using the  website  project. and  i  want to segment them.
For example, i get a semantic image which has Chair, Bicycle ,and TV by the  website  project
how can i change the chair's color to red(255,0,0), the bicycle's color to green(0,255,0), the TV's color to blue(0,0,255).
Then i can segment them easily.

Thanks...

**Comment by sadeepj** [comment]
Hi huihuangz,

Our website http://crfasrnn.torr.vision is only for demonstration purposes. You would have to set up the CRF-RNN code on your own hardware to get the functionality you described.
