### ISSUE TITLE
CUDA toolkit version

### ISSUE THREAD

**Issue by skeeph** [torrvision/crfasrnn#11]
What version do crfasrnn? I am trying to launch code under CUDA Toolkit 7.5, but i got error Check failed: error == cudaSuccess (8 vs. 0)  invalid device function.

Is this because of new CUDA version?

**Comment by Eromera** [comment]
I am using CUDA 7.5 without trouble on a GTX Titan X. Is your GPU compatible? Did you correctly set the device id to use on gpu mode?

**Comment by skeeph** [comment]
@Eromera sorry for dumb questions, but could you give me instructions how to run python demo in gpu mode. I cloned this repo, compiled in gpu mode with cudnn, in python demo file I added strings
net.set_mode_gpu()
net.set_device(0)
But while performing net.predict([im]) I still got error:
F1104 21:28:48.601645  9549 im2col.cu:59] Check failed: error == cudaSuccess (8 vs. 0)  invalid device function

What am I doing wrong?
P.S Sorry for my questions

**Comment by Eromera** [comment]
To activate GPU mode you can just change the line in demo file:
net = caffe.Segmenter(MODEL_FILE, PRETRAINED)
With:
net = caffe.Segmenter(MODEL_FILE, PPRETRAINE, True)

If you check the segmenter.py file in the caffe-crfrnn root you will find that the init function has that bool parameter and by default (false) it activates cpu mode unless you pass a True.

**Comment by skeeph** [comment]
@Eromera thank you. I was doing it right. My mistake was that i didn't unomment lines 
                -gencode arch=compute_50,code=sm_50 \
                -gencode arch=compute_50,code=compute_50
in Makefile.config. Because of this build script didn't generate code for new gpu architecture and i had error while running on gpu
