### ISSUE TITLE
Hi,i run crfasrnn and got a wrong result.

### ISSUE THREAD

**Issue by huihuangz** [torrvision/crfasrnn#110]
I modified the TVG_CRFRNN_new_deploy file according to https://github.com/torrvision/crfasrnn/issues/100 .
i input the example image, but i got a different result as following
input
![input](https://cloud.githubusercontent.com/assets/10891939/24006740/80a5cc7e-0a64-11e7-96d9-83a453df7ac1.jpg)
   output.
![output](https://cloud.githubusercontent.com/assets/10891939/24006757/88b0496c-0a64-11e7-9d2a-7476f30a33c6.png)

Could you please tell me how to fix out ?
Many thanks

**Comment by mohuamuyu** [comment]
You may refer to the issue #86
https://github.com/torrvision/crfasrnn/issues/86

**Comment by huihuangz** [comment]
Thanks
