### ISSUE TITLE
Number of parameters in CRF-RNN layer

### ISSUE THREAD

**Issue by AlexTS1980** [torrvision/crfasrnn#114]
How many parameters are there in CRF-RNN layer? I'm getting a total of 134489759 for FCN-8s and 134491103 for CRF-RNN. Does it mean the CRF-RNN layer has just 1344 parameters?

**Comment by sadeepj** [comment]
@AlexTS1980 I'm not sure how you calculated these numbers. But this is a summary of the tunable weights of CRF-RNN layer:
blobs_[0] - spatial kernel weights, 21 x 21
blobs_[1] - bilateral kernel weights, 21 x 21
blobs_[2] - label compatibility matrix, 21 x 21

Therefore, CRF-RNN layer itself has 3 x 21 x 21 = 1323 tunable parameters. Please refer to the paper for more details.
