### ISSUE TITLE
Meanfield implementation

### ISSUE THREAD

**Issue by raymondchua** [torrvision/crfasrnn#116]
Hi, I am searching for the meanfield implementation in Caffe layers but I can't seem to find it. 
Is it in this repository?

**Comment by bittnt** [comment]
Yes. You probably need to clone the code recursively. https://github.com/torrvision/caffe/ . The implementation for mean-field layer: https://github.com/torrvision/caffe/blob/e7f25fa2bdbb291a067930d60f337d305c128583/src/caffe/layers/multi_stage_meanfield.cpp
