### ISSUE TITLE
Can't to download the caffe model

### ISSUE THREAD

**Issue by Pongroc** [torrvision/crfasrnn#117]
I'm tring to download the trained caffe model from the link :  http://goo.gl/j7PrPZ, but i can't get access to it, could someone share the model with me ?

**Comment by bittnt** [comment]
You need to have access to Google and Google short url.

**Comment by Pongroc** [comment]
Yeah, you're right, i was restricted to access to Google short url, but i can visit Google, could you send me the the original link ?

**Comment by Pongroc** [comment]
Hi, bittnt, could you send me the the original link of the pretrained caffe model ? @bittnt

**Comment by Pongroc** [comment]
From an another closed issue, i have found this link http://bit.ly/2bbOwIb which can be visited,  thx ! Um... a little embarrassed for  answering my own question

**Comment by bittnt** [comment]
Thanks.
