### ISSUE TITLE
Error on building custom caffe version

### ISSUE THREAD

**Issue by cracker0dks** [torrvision/crfasrnn#12]
Hey, I get this error: 

$ sudo make
NVCC src/caffe/util/math_functions.cu
src/caffe/util/math_functions.cu(159): error: kernel launches from templates are not allowed in system files

how can I fix this ?
Im running Ubuntu 14.04 with Atlas and Python

**Comment by bittnt** [comment]
Hey @cracker0dks 

You need to specify the dependencies path in Makefile.config before you do make.

You also do not need sudo.

I hope these would help you.

Thanks.

**Comment by cracker0dks** [comment]
Thanks for you answer. I did. this already but maybe I missed something. Now I'll get this error: 


    NVCC src/caffe/util/math_functions.cu
    src/caffe/util/math_functions.cu(159): error: kernel launches from templates are not allowed in    system files

    1 error detected in the compilation of "/tmp/tmpxft_00000e49_00000000-    10_math_functions.cpp4.ii".

Do you know whats the problem ? cuda ? atlas?

**Comment by bittnt** [comment]
This is probably because some setting was to do with your new glog or cuda. You would better ask questions on caffe user website. 

The software we provided here has been tested on Ubuntu 14.04 with cuda 6.5 and cuda 7.5.

**Comment by cracker0dks** [comment]
thank you :)
