### ISSUE TITLE
 make multi_stage_meanfield.cpp

### ISSUE THREAD

**Issue by zhangyeaixuexi** [torrvision/crfasrnn#121]
when I make  the caffe,the  multi_stage_meanfield.cpp is warnned
src/caffe/layers/multi_stage_meanfield.cpp:72:7: warnning ‘%lf’ expects argument of type ‘double*’, but argument 3 has type ‘float*’ [-Wformat]

**Comment by sadeepj** [comment]
This is a warning that can be safely ignored in this particular case.
