### ISSUE TITLE
retraining

### ISSUE THREAD

**Issue by gopi77** [torrvision/crfasrnn#126]
Hi
Instead of downloading TVG_CRFRNN_COCO_VOC.caffemodel, i would like to generate it by retraining.
1. Do I need to write any new code?
2. Also please provide me the datasets used & 
3. training steps in detail (python command line details preferred)

Regards
Gopi. J

**Comment by sadeepj** [comment]
Please refer to our paper http://www.robots.ox.ac.uk/~szheng/papers/CRFasRNN.pdf for the details of the datasets/training procedure.
