### ISSUE TITLE
Bottom shape mismatch

### ISSUE THREAD

**Issue by SharifAmit** [torrvision/crfasrnn#128]
So i was doing a net surgery from VGG19.caffemodel and vgg19_deploy.prototxt with the given prototxt file in the repo, but the below error is showing everytime. 
F0514 16:58:40.370375 29026 eltwise_layer.cpp:34] Check failed: bottom[0]->shape() == bottom[i]->shape() bottom[0]: 1 21 349 500 (3664500), bottom[1]: 1 21 334 500 (3507000)
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by bittnt** [comment]
Maybe you should make sure the input size is 500x500 or 512x512 rather than 349x500.
