### ISSUE TITLE
Could I run crfasrnn with GPU?

### ISSUE THREAD

**Issue by Fromandto** [torrvision/crfasrnn#13]
After uncommenting 'caffe.set_mode_gpu()' in the python demo script, it complains caffe has no member called set_mode_gpu

and I try to included this function in __init__.py of caffe-crfasrnn/python, still failed.

So is there any way to use gpu for this project, it just takes too long for one pic (~70s), not like the web demo.

Thx in advance

**Comment by Fromandto** [comment]
It seems that the matlab demo script uses gpu mode as default, so I think there must be some problem with my python configuration. Hope someone could help me.

**Comment by Eromera** [comment]
To activate gpu mode you can just add a True at the end of the Segmenter initialization:
net = caffe.Segmenter(MODEL_FILE, PRETRAINED, True)

You can see in the file caffe-crfrnn/python/caffe/segmenter.py that this boolean calls self.set_mode_gpu(). The call "caffe.set_mode_gpu()" does not work because it seems that the caffe version is a bit older, and in previous versions of caffe the mode was set on the net instance like you can see  in segmenter.py file.

**Comment by Fromandto** [comment]
@Eromera  Thank you so much, but now i am trapped by a new problem 

F1126 10:36:25.987403 30768 syncedmem.cpp:16] Check failed: error == cudaSuccess (29 vs. 0)  driver shutting down

same as https://github.com/torrvision/crfasrnn/issues/4

Do you have any idea about how to solve this ? thx

**Comment by Fromandto** [comment]
syncedmem.cpp : 16 looks like this

 CUDA_CHECK(cudaFree(gpu_ptr_));                                                                                    

it seems that this line shuts down gpu thus CUDA_CHECK() reports a error called 'driver shutting down' (actually not a error ? because it's just what CUDA_CHECK expects)

Still don't know why this happends, hope anyone could help. thx.

**Comment by Fromandto** [comment]
the matlab interface works fine with gpu mode on my machine

**Comment by cheer37** [comment]
i got the same problem.
@Fromandto, did you solve this problem?
Thanks.

**Comment by ClaraBing** [comment]
I got the same issue: my matlab demo ran fine, but I got that "driver shutting down" error message when exiting Matlab.
@Fromandto @cheer37 Have you resolved it? Thanks!
