### ISSUE TITLE
Some questions about the source code don't match the paper written?

### ISSUE THREAD

**Issue by sharpstill** [torrvision/crfasrnn#132]
**1. where is weighting filter outputs step in source code?**
![algo1](https://cloud.githubusercontent.com/assets/528004/26662101/5bf17202-46b4-11e7-8a57-50e7bddea492.png)
I notice that the paper said there is weighting filter outputs step , but the source code meanfield_iteration.cpp in line 155 directly omit this step?

**2. the paper and the code written about 1x1 conv don't match?**
in the paper said that the compatibility transform there is 1x1 conv to sovle this weight linear combination:
![com](https://cloud.githubusercontent.com/assets/528004/26662301/91fcdce6-46b5-11e7-9dad-d88c824ffe0f.png)
meanfield_iteration.cpp in line 155~162 directly omit this 1x1 conv?

```
//--------------------------- Compatibility multiplication ----------------
  //Result from message passing needs to be multiplied with compatibility values.
  for (int n = 0; n < num_; ++n) {
    caffe_cpu_gemm<Dtype>(CblasNoTrans, CblasNoTrans, channels_, num_pixels_,
        channels_, (Dtype) 1., this->blobs_[2]->cpu_data(),
        message_passing_.cpu_data() + message_passing_.offset(n), (Dtype) 0.,
        pairwise_.mutable_cpu_data() + pairwise_.offset(n));
  }
```

2. in meanfield_iteration.cpp line : 175:
`vector<bool> eltwise_propagate_down(2, true);`
why is 2 set here, because sum_top_vec_ only have 2 element in it?

**3. in meanfield_iteration.cpp line : 182:**
`caffe_cpu_gemm<Dtype>(CblasNoTrans, CblasTrans, channels_, channels_,
                          num_pixels_, (Dtype) 1., pairwise_.cpu_diff() + pairwise_.offset(n),
                          message_passing_.cpu_data() + message_passing_.offset(n), (Dtype) 1.,
this->blobs_[2]->mutable_cpu_diff());`
why transpose message_passing_ matrix here?

**4. again in line 190**
`caffe_cpu_gemm<Dtype>(CblasTrans, CblasNoTrans, channels_, num_pixels_, 
                          channels_, (Dtype) 1., this->blobs_[2]->cpu_data(),
                          pairwise_.cpu_diff() + pairwise_.offset(n), (Dtype) 0.,
                          message_passing_.mutable_cpu_diff() + message_passing_.offset(n));`
why transpose this->blobs_[2] here？

**Comment by bittnt** [comment]
Hey, you should check both multi_stage_meanfield as well as the meanfield_iteration code.

**Comment by sadeepj** [comment]
Hi @sharpstill,

Unfortunately, we don't have enough bandwidth to answer this kind of queries in detail. But please note that there's no discrepancy between what's written in the paper and the implementation. Please find my short answers to your queries below:

1.) [Line 143](https://github.com/torrvision/caffe/blob/d779ee369bf86739bc225d99e78aefa040da199f/src/caffe/layers/meanfield_iteration.cpp#L143) - [line 153](https://github.com/torrvision/caffe/blob/d779ee369bf86739bc225d99e78aefa040da199f/src/caffe/layers/meanfield_iteration.cpp#L153) of meanfield_iteration.cpp does exactly this weighting.

2.) [Line 155](https://github.com/torrvision/caffe/blob/d779ee369bf86739bc225d99e78aefa040da199f/src/caffe/layers/meanfield_iteration.cpp#L155) does this. It's just a different way of implementing it, but the effect is the same.

3.) & 4.) Again, these computations agree with the steps described in the paper. Please refer to the documentation of the relevant Caffe functions and the BLAS API for help.
