### ISSUE TITLE
Python Layer, Images Size

### ISSUE THREAD

**Issue by mateovilla2** [torrvision/crfasrnn#135]
Hello, I would like to ask 2 questions concerning the input layer :

CanI use a Python Layer( the Python layer provided in the FCN project) instead of the LMDB layer for the Input Images and Labels ? It doesn't give troubles when loading the .caffemodel?  (obviously, modifying the net in the .prototxt file).

Can I use image of arbitrary size (max 512x512 pixels) , without padding ?

Thanks,

Mateo

**Comment by bittnt** [comment]
You can, but you are at your own risk doing so.
