### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by mateovilla2** [torrvision/crfasrnn#137]
Hello, I'm new in docker, I would like to know how to run a container with this caffe version ( with crf as rnn layers,etc). The main caffe docker version doesn't support your model. Anyone has an idea how to do it ?

Thank you for any suggestion or indication,

Cordially,

Mateo

**Comment by bittnt** [comment]
I actually built one:https://hub.docker.com/r/bittnt/caffecrfasrnn/
You should be able to do so by using the one: https://github.com/torrvision/caffe/tree/crfrnn/docker, although you might or might not see accuracy loss for the new version due to the change in the new code, e.g. crop layer.
