### ISSUE TITLE
Crop_param

### ISSUE THREAD

**Issue by AlexTS1980** [torrvision/crfasrnn#138]
The error is 

`Message type "caffe.LayerParameter" has no field named "crop_param"
`

Is there any way to implement crop_param in the crf-rnn's version of caffe? The layer in my network is

```
layer {
  name: "score_final"
  type: "Crop"
  bottom: "upscore5"
  bottom: "data_shape"
  top: "score_final"
  crop_param {
    axis: 2
    offset: 50
  }
}
```
When I remove the crop_param detail, the deploy seems to just simply freeze, i.e it tries to 

```
I0710 00:51:27.730908 19334 layer_factory.hpp:76] Creating layer score_final
I0710 00:51:27.730916 19334 net.cpp:111] Creating Layer score_final
I0710 00:51:27.730921 19334 net.cpp:478] score_final <- upscore5  
I0710 00:51:27.730926 19334 net.cpp:478] score_final <- data_shape
I0710 00:51:27.730932 19334 net.cpp:434] score_final -> score_final
```

and nothing happens/freezes. Any suggestions?

**Comment by bittnt** [comment]
In current default crfasrnn caffe, crop_param is implemented differently. You do not need to specify the crop parameters,

I the latest caffe with crfasrnn, it has the latest crop_param already.

**Comment by AlexTS1980** [comment]
I fully reinstalled crfrnn's caffe but still get the erro


```
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 250:14: Message type "caffe.LayerParameter" has no field named "crop_param".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0724 03:45:10.407212 32471 upgrade_proto.cpp:932] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: ../models/mcn-train_finetune11.prototxt
*** Check failure stack trace: ***
```

**Comment by bittnt** [comment]
Because you are using the version that has no crop. Try to use the default one.

**Comment by AlexTS1980** [comment]
The thing is, the input in my network for training/testing is not an image. In order to output an image-sized map/mask, I have an additional input ("data_shape" in deploy mode) that is the size of the image, e.g. 600x1000. When I run an implementation without this second input, it's all fine, but with "data_shape" it's a problem, the same one as I described above (freezes w/out an error output). 

Specific problem seems to be in net.cpp, immediately after line 434 in appending a top of the layer, but I'm not very good at C++, so don't quite understand what to change in the code.

**Comment by AlexTS1980** [comment]
Alright, I did it! The trick was to download the zipped file with the new code for the crop layer instead of cloning it. It works fine, just the CRF-RNN layer trains very slowly (0.1-0.2 iteration/sec).
