### ISSUE TITLE
Failed to parse NetParameter file: TVG_CRFRNN_COCO_VOC.caffemodel

### ISSUE THREAD

**Issue by cuekoo** [torrvision/crfasrnn#14]
I am trying to run the python demo, but got the following error:

    I1201 20:32:24.720659 13679 net.cpp:221] Network initialization done.
    I1201 20:32:24.720666 13679 net.cpp:222] Memory required for data: 1287634208
    [libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large    protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted    for security reasons.  To increase the limit (or to disable these warnings), see    CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
    [libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was   537967400
    F1201 20:32:25.981808 13679 upgrade_proto.cpp:638] Check failed:  ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file:  TVG_CRFRNN_COCO_VOC.caffemodel
    *** Check failure stack trace: ***
    [1]    13679 abort (core dumped)  python crfasrnn_demo.py

**Comment by bittnt** [comment]
Hey, 
It is hard to tell what's happened here, maybe you should provide more information.

This could either due to the model is not correct. Maybe you should try to re-download the model, or you should give the correct path to the model in that demo python script.

**Comment by cuekoo** [comment]
Thank you Shuai.

 The problem was solved by re-download the model with `wget` (previously I used Chromium). By the way, it will be appreciated if there is an "in wall" link of the model for Chinese users.
