### ISSUE TITLE
Cannot align apparently disconnected blobs.

### ISSUE THREAD

**Issue by AlexTS1980** [torrvision/crfasrnn#141]
My data is 16x4096x8x8 (fc7 layer from FCN), labels 16x1x250x250 (the actual image size is 250x250x3), the crop layer (the one that outputs Q0 and coarse afte splitting) is size 16x2x250x250 (2 is the number of classes) aligned to the size of the label. When I use crf-rnn caffe implementation, I get an

`Check failed: this->net_->bottom_vecs()[layer_ind].size() > 0 (0 vs. 0) Cannot align apparently disconnected blobs.`

error. As I understand, this comes from the fact that label layer isn't used before crop. 

Not sure how to fix this error. It doesn't come up in the vanilla caffe implementation.

**Comment by sylqiu** [comment]
I have the same problem. Did you manage to fix it?
