### ISSUE TITLE
Out of memory when using batch_size higher than 3 during training

### ISSUE THREAD

**Issue by martinkersner** [torrvision/crfasrnn#20]
Hi!

I am trying to train *CRF-RNN* using part of VOC 2012 data but when I set *batch_size* higher than 3, I receive `error == cudaSuccess (2 vs. 0) out of memory`. It is quite surprising to me because I am using nVidia Tesla K40, so there should be enough memory. Moreover, in a log there is not required more memory than I possess. I still can train with only 3 images per batch but I expect that the loss is going to drop very slowly. 

**Questions**
* Did somebody encounter similar issue, or is it just problem on my side?
* How large batch size was used to create publicly avaliable model? (I did not find any mention about it in paper)

Thank you!

Martin

**Comment by bittnt** [comment]
1. Setting batch_size higher than 3 is possible when the images with lower resolution than 500x500, or the number of labels are less than 21.
2. We used batch_size =1 to create this model.

**Comment by martinkersner** [comment]
Thank you for prompt response! I will try it out.
