### ISSUE TITLE
TImages 

### ISSUE THREAD

**Issue by limorbagizada** [torrvision/crfasrnn#26]
Hii

I had installed the crfasrnn demo and the code worked well.

What is the image database that have been used in order to train the model? Do you use a popular image database like image net or your own data source?
Can I have access to this database?

Thanks

**Comment by bittnt** [comment]
@limorbagizada Thanks. Please refer to our paper for the dataset queries. We used MS COCO and Pascal VOC dataset. They are all public available, and free to download for research purpose.
http://www.robots.ox.ac.uk/~szheng/papers/CRFasRNN.pdf
