### ISSUE TITLE
Instance Segmentaion

### ISSUE THREAD

**Issue by limorbagizada** [torrvision/crfasrnn#27]
As I understand according to the paper and the video-lecture: http://www.robots.ox.ac.uk/~szheng/CRFasRNN.html :
the demo-segmentation can separate multiple object close to each other (e.g separate 3 close boats instead of recognize the as a single big bout), and also it can add Ground Truth layer which gives more accurate result and draws the contour of each object.

when I run the demo I cant see these abilities, how can I add them?

thanks

**Comment by bittnt** [comment]
@limorbagizada  CRFasRNN ICCV 2015 only contains the semantic image segmentation application. However, you should easily adapt this to other applications e.g. instance segmentation. 

If you are interested in using it for instance segmentation, there are various papers alone this line, e.g. Berkeley Simultaneously Segmentation and Detection (ECCV 2014 paper).
