### ISSUE TITLE
How to work with higher resolution images?

### ISSUE THREAD

**Issue by tharun2011** [torrvision/crfasrnn#32]
I am getting runtime error when I use higher resolution images.
**self.blobs[in_].data[...] = blob
ValueError: could not broadcast input array from shape (1,3,700,700) into shape (1,3,500,500)_
**
I am having trouble figuring out where the self.blobs[in_].data[...] numpy shape is initialized.
Need suggestions for debugging.

**Comment by bittnt** [comment]
Hi, just modify the prototxt. Change 
input_dim: 500
input_dim: 500 
To:
input_dim: 700
input_dim: 700
