### ISSUE TITLE
MultiStageMeanField GPU implementation seg faults

### ISSUE THREAD

**Issue by mrajchl** [torrvision/crfasrnn#33]
The filter expects an input image of size Nx3xHxW. When a grayscale/monochrome image is provided, the GPU implementation seg faults (CPU does not). I guess that there is an automatic alloc with zero filling when using the CPU, which does not exist in the CUDA code. 

Workaround: concatenate the grayscale image to have three channels. See config below:

layer {
  name: "rgb"
  bottom: "data"
  bottom: "data"
  bottom: "data"
  top: "rgb"
  type: "Concat"
  concat_param {
    axis: 1
  }
}

**Comment by bittnt** [comment]
If you have Grayscale image, just make sure to repeat the same pixel value into three channels. Then you should be able to use the same network. 

This is how we handle the gray image in the demo website at the moment.

**Comment by JoestarK** [comment]
Hello,
I also got seg faults using GPU for training.Did you fix it?

**Comment by mrajchl** [comment]
Yes, the solution from above. You need to concatenate the monochrome channels to RGB, then it works.
