### ISSUE TITLE
error encountered when running demo in python script

### ISSUE THREAD

**Issue by Robert0812** [torrvision/crfasrnn#34]
I can go through the "make" step, with model downloaded. When running the demo by:

```
python crfasrnn_demo.py
```

error encountered. Please tell me how I can fix this.

Traceback (most recent call last):
  File "crfasrnn_demo.py", line 38, in <module>
    net = caffe.Segmenter(MODEL_FILE, PRETRAINED)
  File "../caffe-crfrnn/python/caffe/segmenter.py", line 19, in **init**
    caffe.Net.**init**(self, model_file, pretrained_file)
Boost.Python.ArgumentError: Python argument types in
    Net.**init**(Segmenter, str, str)
did not match C++ signature:
    **init**(_object*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
    __init__(_object*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)

**Comment by bittnt** [comment]
Hi looks like the error is caused by different cpp compiler. Maybe you can either change the gcc compile or change the _caffe.cpp in the python/caffe folder.

**Comment by sirim** [comment]
I got similar issue except the last two lines. No problem during make. I recently downgraded from gcc 5.4 to 5.3. Could that be the issue? but again no errors or warning during make. Please help

Traceback (most recent call last):
  File "crfasrnn_demo.py", line 41, in <module>
    net = caffe.Segmenter(MODEL_FILE, PRETRAINED)
  File "/home/userx/crfasrnn-master-gpu/caffe-crfrnn/python/caffe/segmenter.py", line 22, in __init__
    self.set_mode_gpu()
Boost.Python.ArgumentError: Python argument types in
    Net.set_mode_gpu(Segmenter)
did not match C++ signature:
    set_mode_gpu(caffe::PyNet {lvalue})

**Comment by tsingjinyun** [comment]
@sirim ，i have meet the same problem as yours(i use the code version of  https://github.com/hyenal/crfasrnn ), and do you solved it?
