### ISSUE TITLE
Object delineation-edge between segmented obects

### ISSUE THREAD

**Issue by AlexTS1980** [torrvision/crfasrnn#38]
I was able to extract some objects from a challenging image (http://datascience.stackexchange.com/questions/10809/image-segmentation-with-a-challenging-background): lots of shadows, object/background colors are indistinguishable and so on. Some cows on the  image are occluded: there's one cow behind another, although both a well identified. 

Here's my question: how do I delineate these 2 objects. If crf-rnn recognizes that they are separate, this should be somehow reflected. I believe, if these were objects of different classes, pixels would have different labels. But what if the occluded object is of the same class? 

thanks

**Comment by bittnt** [comment]
@AlexTS1980 This is still a open question, it is called instance segmentation. MSRA has a solution http://arxiv.org/pdf/1512.04412.pdf. Other solution is also interesting: http://arxiv.org/abs/1511.04517.  However, none of them have open source except Berkeley SDS (https://github.com/bharath272/sds_eccv2014). We hope to provide our own open source solution. e.g. http://arxiv.org/abs/1511.08250 It would also be interesting to see other solutions from the visitors of this repository.

**Comment by AlexTS1980** [comment]
@bittnt thanks; I'm not a computer vision specialist. When I run crf-rnn, the algorithm often correctly segments animals, even when they are occluded, as on the picture. Therefore, there should be some shape detector that tells one animal from another and labels then correctly. Therefore, it is able to tell between two objects of the same class, but how?  

![3cows](https://cloud.githubusercontent.com/assets/8479872/14078652/8bbf0c00-f4ef-11e5-976e-b24685979f42.png)

**Comment by AlexTS1980** [comment]
well I ended up publishing a paper with my own solution for instance segmentation. It's just the first step, now I'm working on the improvement.

Check out 'Bootstrapping Labelled Dataset Construction for Cow Tracking and Behavior Analysis'
