### ISSUE TITLE
Compatibility with AWS / nvidia Grid GPU

### ISSUE THREAD

**Issue by AKSHAYUBHAT** [torrvision/crfasrnn#4]
Have you or anyone else tested this code with AWS G2 instances? 

I tried testing and even after compiling your version of caffe and running make runtest, the code did not work with GPU (Failed with core dump). 

I also replaced the commented out line in python code to enable GPU mode
```python
#caffe.set_mode_gpu()
net.set_mode_gpu()
```
The CPU code seemed to work, but threw an error when trying to show the image, due to lack of display.
Is this happening due to lack of memory since AWS GPUs have only 4Gb memory? 

Thanks,

**Comment by amiltonwong** [comment]
Did you place Makefile.config file?

**Comment by AKSHAYUBHAT** [comment]
Yes, I edited Makefile.config, enabled cudnn, and ran
```` 
make test 
make runetest
```` 
Have you had success with the GPU enabled version?

**Comment by bittnt** [comment]
@AKSHAYUBHAT Yes. You need 6GB GPU memory to run this. Try this: https://github.com/BVLC/caffe/pull/2016 or similar solution.

**Comment by AKSHAYUBHAT** [comment]
@bittnt Your version of caffe already has this change merged. 

The error I got is was similar to this one, which is a known side effect of the pull request.
````
F0305 21:14:53.266198 1810 syncedmem.cpp:16] Check failed: error == cudaSuccess (29 vs. 0) driver shutting down
```
I will check again if the error appeared after completion or while loading the model. 

https://github.com/torrvision/crfasrnn/blob/master/caffe-crfrnn/src/caffe/layers/base_conv_layer.cpp

**Comment by Fromandto** [comment]
@AKSHAYUBHAT  Hello I came into the same problem

F1126 10:36:25.987403 30768 syncedmem.cpp:16] Check failed: error == cudaSuccess (29 vs. 0)  driver shutting down

Have you got any idea about how to solve this ? thx in advance

**Comment by Fromandto** [comment]
syncedmem.cpp : 16 looks like this

CUDA_CHECK(cudaFree(gpu_ptr_));

it seems that this line shuts down gpu thus CUDA_CHECK() reports a error called 'driver shutting down' (actually not a error ? because it's just what CUDA_CHECK expects)

Still don't know why this happends, hope anyone could help. thx.

**Comment by Fromandto** [comment]
the matlab interface works fine with gpu mode on my machine

**Comment by bittnt** [comment]
@Fromandto I saw similar errors before. This is mostly due to the incorrect setting in cuda compiling instruction in Makefile.config. Once i set it correctly, everything works fine.

**Comment by iceflame89** [comment]
@Fromandto 
I got the same problem, Did you fix it?

**Comment by zimenglan-sysu-512** [comment]
@bittnt I got the same problem, how to set `cuda` configuration in `Makefile.config` file to make everything work fine?

**Comment by bittnt** [comment]
@zimenglan-sysu-512 This is due to the https://github.com/BVLC/caffe/pull/2016. If you see this error, please undo this pull request.

**Comment by tharun2011** [comment]
Building on cpu worked fine. But when tried to build on gpu, having the following error:
Steps performed:
1)Uncommented cudnn.
2)Commented cpu.
3)Ran 'make' command.
Need suggestions to solve this issue.
```
./include/caffe/util/device_alternate.hpp:35:18: warning: cuda.h: No such file or directory
./include/caffe/util/device_alternate.hpp:36:26: warning: cuda_runtime.h: No such file or directory
./include/caffe/util/device_alternate.hpp:37:20: warning: curand.h: No such file or directory
./include/caffe/util/device_alternate.hpp:38:48: warning: driver_types.h: No such file or directory
In file included from ./include/caffe/util/device_alternate.hpp:40,
                 from ./include/caffe/common.hpp:18,
                 from ./include/caffe/blob.hpp:4,
                 from ./include/caffe/filler.hpp:10,
                 from src/caffe/layers/cudnn_conv_layer.cpp:4:
./include/caffe/util/cudnn.hpp:5:19: warning: cudnn.h: No such file or directory
In file included from ./include/caffe/util/device_alternate.hpp:40,
                 from ./include/caffe/common.hpp:18,
                 from ./include/caffe/blob.hpp:4,
                 from ./include/caffe/filler.hpp:10,
                 from src/caffe/layers/cudnn_conv_layer.cpp:4:
./include/caffe/util/cudnn.hpp:17: error: ‘cudnnGetErrorString’ declared as 
an ‘inline’ variable
./include/caffe/util/cudnn.hpp:17: error: ‘cudnnStatus_t’ was not declared i   $
n this scope
./include/caffe/util/cudnn.hpp:17: error: expected ‘,’ or ‘;’ before ‘         $
{’ token
make: *** [.build_release/src/caffe/layers/cudnn_conv_layer.o] Error 1

```

**Comment by bittnt** [comment]
This is because the caffe customised version does not support cudnn latest
version (4) yet. You could change the cudnn.hpp file a bit following the
error message.

**Comment by tharun2011** [comment]
@bittnt 
Thanks.
But, still facing the issue.
`syncedmem.cpp:16] Check failed: error == cudaSuccess (29 vs. 0) driver shutting down`
Should I undo the below changes?
https://github.com/shelhamer/caffe/commit/839b0502648a5dcf056c3f4a6ace1d0198e6b03e

**Comment by bittnt** [comment]
which cudnn version do you use?

**Comment by tharun2011** [comment]
I have used cuda-7. Didn't use cudnn.

**Comment by bittnt** [comment]
Please comment the cudnn in Makefile.config then it should work.

**Comment by tharun2011** [comment]
I did comment the cudnn. I could able to build it. But when running the demo, I am facing the following error.
` syncedmem.cpp:16] Check failed: error == cudaSuccess (29 vs. 0) driver shutting down`

**Comment by cheer37** [comment]
I got the same situation.
How did you solve this problem?

**Comment by bittnt** [comment]
This error message shows:
*cudaErrorCudartUnloading*  This indicated an issue with calling API
functions during the unload process of the CUDA runtime in prior
releases. *Deprecated:
<http://horacio9573.no-ip.org/cuda/deprecated.html#_deprecated000042>*This
error return is deprecated as of CUDA 3.2.
I guess you should check my previous Makefile.config Make sure below
information are consistency to your GPUs:

For titan X or maxwell GPUs, try:
CUDA_ARCH := -gencode arch=compute_30,code=sm_30 \
 -gencode arch=compute_35,code=sm_35
 -gencode arch=compute_50,code=sm_50 \
 -gencode arch=compute_50,code=compute_50

Remember to make clean and then make -j 8

**Comment by nrasiwas** [comment]
@bittnt I am getting the same error when I exit the program. I do have the correct segmented image. 

`syncedmem.cpp:16] Check failed: error == cudaSuccess (29 vs. 0) driver shutting down`

I am using cuda-7.0 with no cudnn option on AWS g2.2xlarge (its a Kepler GK 104 [GRID K520] gpu card)

**Comment by cheer37** [comment]
I know my architecture exactly.
It's compute_50,sm_50.
So, I dont have to specify others too.
But I have tried to do it, nothing change, error goes still.

**Comment by bittnt** [comment]
This error is side effect of PR2016 to the latest caffe-master, please
check related solution there. It will affect all caffe convolution layer
with caffe engine.


On Monday, 14 March 2016, cheer37 <notifications@github.com> wrote:

> I know my architecture exactly.
> It's compute_50,sm_50.
> So, I dont have to specify others too.
> But I have tried to do it, nothing change, error goes still.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/torrvision/crfasrnn/issues/4#issuecomment-196132886>.
>


-- 
-
郑帅
Shuai Zheng (Kyle)
http://kylezheng.org/

**Comment by cheer37** [comment]
Thanks bittnt for your kind guidance.
I will check it.

**Comment by JoestarK** [comment]
I got the same problem:
syncedmem.cpp:16] Check failed: error == cudaSuccess (29 vs. 0) driver shutting down

Did you fix it? I also couldn't get the right segmentation.When I used the GPU to train my data, I got 'core dumped'

**Comment by bittnt** [comment]
@JoestarK Sorry to hear that. I guess this could because you did not add file spatial.par and bilateral.par on the path you submit your job to GPUs.

**Comment by JoestarK** [comment]
@bittnt Thanks for your reply.I tested the crfasrnn_demo.py just now,it worked well on CPU and could get the right segmentation.Is there any solution to GPU? And, what did you mean 'add file spatial.par and bilateral.par on the path I submit my job to GPUs' ? I just copied these two files to the layers file and the caffe root.

**Comment by nrasiwas** [comment]
@bittnt - I am still not able to resolve the 

`syncedmem.cpp:16] Check failed: error == cudaSuccess (29 vs. 0) driver shutting down`

error. I see that you mention its a side effect of PR2016. But if I remove the PR2016, I get the out of memory error

`Check failed: error == cudaSuccess (2 vs. 0)  out of memory`

Can you please suggest what should I do to not get either of the errors? When you say  please
check related solution there - where exactly do you mean?

**Comment by bittnt** [comment]
@nrasiwas 
Sorry to hear that.

1. cudaSuccess (29 vs. 0) error could be caused by PR2016. But this does not affect me in most cases. I think if you use cuda7.5+ubuntu14.04, this should be avoid.

2. cudaSuccess (2 vs. 0) out of memory means you probably need a 12-GB GPU like titan X or K40 to run the program. This is often the case during training a VGG-FCN-8-CRF-RNN model. But if you have PR2016, you should be able to at least run the inference with this model at a GPU with 6-GB memory.

**Comment by jeremy-rutman** [comment]
I also get the  Check failed: error == cudaSuccess (29 vs. 0) error
I have been trying to make without cudnn - is this possible?
I use a K80 and have tried the line CUDA_ARCH :=	-gencode arch=compute_37,code=sm_37 
but this also does not work...
When I tried downloading cudnn v2 and copying the files 
cp cudnn-6.5-linux-x64-v2/libcudnn* /usr/local/cuda/lib64
cp cudnn-6.5-linux-x64-v2/cudnn.h  /usr/local/cuda/include/
and compiling with cudnn on, the error still happends.

**Comment by bittnt** [comment]
You could try changing these in the Makefile.config

CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
-gencode arch=compute_20,code=sm_21 \
-gencode arch=compute_30,code=sm_30 \
-gencode arch=compute_35,code=sm_35 \
#-gencode arch=compute_50,code=sm_50 \
#-gencode arch=compute_50,code=compute_50


to
CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
-gencode arch=compute_20,code=sm_21 \
-gencode arch=compute_30,code=sm_30 \
-gencode arch=compute_35,code=sm_35 \
-gencode arch=compute_50,code=sm_50 \
-gencode arch=compute_50,code=compute_50

**Comment by jeremy-rutman** [comment]
Ok I tried this verbatim, same error. 
Is there a merged version of crfasrnn with the main branch ?

**Comment by JoestarK** [comment]
@jeremy-rutman Maybe [this version](https://github.com/mtourne/caffe) will be better. This works well for training my own data using GPU

**Comment by jeremy-rutman** [comment]
Thanks, I tried that branch and it compiles and runs with gpu 
(which I enable by setting 
net = caffe.Segmenter(MODEL_FILE, PRETRAINED,True)
in crfasrnn_demo.py)
We have a K80 and are seeing runtimes of ~13s, as opposed to ~1s on the web demo .
Is there any barrier to getting full gpu usage here?

**Comment by bittnt** [comment]
I am glad to hear that it works for you.

I do not think you use the GPU to compile the code. Running at 13s means
you are using purely CPU version of the caffe.

I still think you should be able to use the code in this branch, there are
some problems with your setting in ./bashrc or the cuda you are using.
Maybe you did not make clean before you do make -j 12. The code on this
branch has been tested on Mac OSX / Red Hat Enterprise Linux / Ubuntu 14.0X
with CUDA 6.5, 7.0, and 7.5.

**Comment by bittnt** [comment]
If you have K80 GPU, then why not try to undo PR2016?
See this: https://github.com/BVLC/caffe/pull/2016

As a reminder, the static buffer causes this crash on exit:

F0305 21:14:53.266198 1810 syncedmem.cpp:16] Check failed: error ==
cudaSuccess (29 vs. 0) driver shutting down

this is a known side effect.

**Comment by ucasqcz** [comment]
@bittnt ,i did not use the most newly BVLC/caffe#2016
but i got the same error 
Check failed: error == cudaSuccess (29 vs. 0) driver shutting down,
is there some other reason?
