### ISSUE TITLE
Hi,How can I train a new classification?

### ISSUE THREAD

**Issue by wuhang** [torrvision/crfasrnn#40]
Hi all,
I want to train a classification on the clothing, such as dresses, How can I do it?
Thank you,
Hang

**Comment by bittnt** [comment]
@wuhang Thanks. If you are talking about pixel-wise classification, you should find out some dataset. and prepare the lmdb. After this, start to train with your favourite CNN architecture, e.g. FCN-32 or FCN-8. Then you should make use the code here to refine the CNN prediction. See the example and CRF-RNN training script from others.
