### ISSUE TITLE
Error when using 'make'

### ISSUE THREAD

**Issue by jpsquare** [torrvision/crfasrnn#44]
I get this error when I run make 

CXX src/caffe/net.cpp
In file included from src/caffe/net.cpp:13:0:
./include/caffe/util/io.hpp:12:18: fatal error: hdf5.h: No such file or directory
 #include "hdf5.h"
                  ^
compilation terminated.
Makefile:469: recipe for target '.build_release/src/caffe/net.o' failed
make: *** [.build_release/src/caffe/net.o] Error 1

I did check for the hdf5.h file and found it in this location:

/usr/include/hdf5/serial/hdf5.h
/usr/include/opencv2/flann/hdf5.h

I get the same error when I run 'sudo make'
what could be the issue? ... has it got something to do with the makefile.config file?

Any help would be appreciated. Thanks

**Comment by bittnt** [comment]
Hi, you should modify makefile.config to set the path correct. see details in :+1: http://caffe.berkeleyvision.org/installation.html

If you have any compiling related problems, you should post on caffe-user[https://groups.google.com/forum/#!forum/caffe-users].

**Comment by jpsquare** [comment]
Thankyou @bittnt , I changed the makefile.config to add a path for the hdf5 library, then the compilation finished without any issues.
