### ISSUE TITLE
Unknown enumeration value of "MULTI_STAGE_MEANFIELD" for field "type"

### ISSUE THREAD

**Issue by snakehaihai** [torrvision/crfasrnn#45]
After running /solve.py  from https://github.com/martinkersner/train-CRF-RNN
the following error pop up

I0428 23:40:04.491811 27105 caffe.cpp:183] Using GPUs 0
I0428 23:40:04.587026 27105 solver.cpp:54] Initializing solver from parameters: 
test_iter: 261
test_interval: 1333
base_lr: 1e-13
display: 50
max_iter: 100000
lr_policy: "fixed"
momentum: 0.99
weight_decay: 0.0005
snapshot: 1000
snapshot_prefix: "/home/snake/caffe_crfrnn/train-CRF-RNN-master/snapshot/train"
solver_mode: GPU
device_id: 0
net: "/home/snake/caffe_crfrnn/train-CRF-RNN-master/TVG_CRFRNN_COCO_VOC_TRAIN_3_CLASSES.prototxt"
test_initialization: false
I0428 23:40:04.587134 27105 solver.cpp:96] Creating training net from net file: /home/snake/caffe_crfrnn/train-CRF-RNN-master/TVG_CRFRNN_COCO_VOC_TRAIN_3_CLASSES.prototxt
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 213:3: Unknown enumeration value of "MULTI_STAGE_MEANFIELD" for field "type".
F0428 23:40:04.587803 27105 upgrade_proto.cpp:932] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /home/snake/caffe_crfrnn/train-CRF-RNN-master/TVG_CRFRNN_COCO_VOC_TRAIN_3_CLASSES.prototxt

The MULTI_STAGE_MEANFIELD is build but there was some warning
CXX src/caffe/layers/eltwise_layer.cpp
src/caffe/layers/multi_stage_meanfield.cpp: In instantiation of ‘void caffe::MultiStageMeanfieldLayer::LayerSetUp(const std::vectorcaffe::Blob<Dtype>&, const std::vectorcaffe::Blob<Dtype>&) [with Dtype = float]’:
src/caffe/layers/multi_stage_meanfield.cpp:258:1: required from here
src/caffe/layers/multi_stage_meanfield.cpp:72:83: warning: format ‘%lf’ expects argument of type ‘double’, but argument 3 has type ‘float’ [-Wformat=]
fscanf(pFile, "%lf", &this->blobs_[0]->mutable_cpu_data()[i * channels_ + i]);
^
src/caffe/layers/multi_stage_meanfield.cpp:79:83: warning: format ‘%lf’ expects argument of type ‘double’, but argument 3 has type ‘float’ [-Wformat=]
fscanf(pFile, "%lf", &this->blobs_[1]->mutable_cpu_data()[i * channels_ + i]);
^
src/caffe/layers/multi_stage_meanfield.cpp: In member function ‘void caffe::MultiStageMeanfieldLayer::LayerSetUp(const std::vectorcaffe::Blob<Dtype>&, const std::vectorcaffe::Blob<Dtype>&) [with Dtype = float]’:
src/caffe/layers/multi_stage_meanfield.cpp:72:7: warning: ignoring return value of ‘int fscanf(FILE, const char, ...)’, declared with attribute warn_unused_result [-Wunused-result]
fscanf(pFile, "%lf", &this->blobs_[0]->mutable_cpu_data()[i * channels_ + i]);
^
src/caffe/layers/multi_stage_meanfield.cpp:79:7: warning: ignoring return value of ‘int fscanf(FILE, const char, ...)’, declared with attribute warn_unused_result [-Wunused-result]
fscanf(pFile, "%lf", &this->blobs_[1]->mutable_cpu_data()[i * channels_ + i]);
^
src/caffe/layers/multi_stage_meanfield.cpp: In member function ‘void caffe::MultiStageMeanfieldLayer::LayerSetUp(const std::vectorcaffe::Blob<Dtype>&, const std::vectorcaffe::Blob<Dtype>&) [with Dtype = double]’:
src/caffe/layers/multi_stage_meanfield.cpp:72:7: warning: ignoring return value of ‘int fscanf(FILE, const char, ...)’, declared with attribute warn_unused_result [-Wunused-result]
fscanf(pFile, "%lf", &this->blobs_[0]->mutable_cpu_data()[i * channels_ + i]);
^
src/caffe/layers/multi_stage_meanfield.cpp:79:7: warning: ignoring return value of ‘int fscanf(FILE, const char, ...)’, declared with attribute warn_unused_result [-Wunused-result]
fscanf(pFile, "%lf", &this->blobs_[1]->mutable_cpu_data()[i * channels_ + i]);
^

anyidea how to solve it?

**Comment by bittnt** [comment]
The caffe code base has been updated, if you are using this code. MULTI_STAGE_MEANFIELD should be defined in src/caffe/proto/caffe.proto file, please check if the syntax is the same.

**Comment by snakehaihai** [comment]
I found out the problem. Just some script use layers instead of layer   and  CONVOLUTION instead of "Convolution". Is old caffe naming and new caffe type naming issue
After i change all those small things, it works

Ok can close the topic.

**Comment by bittnt** [comment]
Glad to know this. Thanks.

**Comment by anguszxd** [comment]
Hi @snakehaihai , I meet the same problem when I try `solve.py` , and I get error report `Error parsing text-format caffe.NetParameter: 224:3: Unknown enumeration value of "MULTI_STAGE_MEANFIELD" for field "type".` Would you like to share your solution in detail? Thank you very much!

**Comment by bittnt** [comment]
@anguszxd what caffe are you using? I have changed the caffe code to be more compatible with latest caffe, you should therefore use the new prototxt in added in this repository. Thanks.

**Comment by anguszxd** [comment]
@bittnt Thank you for your reply. I've solved this problem. Martin's prototxt file is out of date and is not compatible with the latest Caffe. I modify the prototxt file according to your `TVG_CRFRNN_new_deploy.prototxt` and it works.
Thanks for your help and best wishes !
