### ISSUE TITLE
Determining the inference layer parameters

### ISSUE THREAD

**Issue by nbalakumaran** [torrvision/crfasrnn#49]
Hello,

In crfasrnn paper, section 6
> The compatibility transform parameters of the CRF-RNN were initialized using the Potts model, and kernel width and weight parameters were obtained from a cross-validation process

Can you please shed some more light into the cross-validation process?

Thanks

**Comment by bittnt** [comment]
For cross validation, you simply set up a pool of parameter candidates, and then go through each combination of them.
