### ISSUE TITLE
Cuda versions

### ISSUE THREAD

**Issue by twerdster** [torrvision/crfasrnn#5]
Are there cuda versions of this code? I can only see the forward and backward cpu versions and no .cu files. The runtime is very slow.

**Comment by sadeepj** [comment]
Please note that we have released only the CPU version of our code at this point. Furthermore, code of this public version is not optimized for speed or memory.

**Comment by cracker0dks** [comment]
is their a chance you release the cuda version as well?

**Comment by darshanhegde** [comment]
+1 for CUDA version of the code.

**Comment by sadeepj** [comment]
Closing old issues.
