### ISSUE TITLE
opencv v3.1.0

### ISSUE THREAD

**Issue by AlexTS1980** [torrvision/crfasrnn#51]
I'v recently installed new version of cv2, 3.1.0. Now I've got problems install CRFasRNN: 

In window_data_layer.cpp I commented 

```
#if CV_VERSION_MAJOR == 3
const int CV_LOAD_IMAGE_COLOR = cv::IMREAD_COLOR;
#endif
```
 which solved the problem of ‘const int CV_LOAD_IMAGE_COLOR’ redeclared as different kind of symbol. 

Now when processing  compute_image_mean.o I keep getting 

`undefined reference to `cv::imread(cv::String const&, int)'`

Can I use opencv v3 with CRF at all, or should I roll back to 2.4? It seems there's some format incompatibility. 

cheers

**Comment by AlexTS1980** [comment]
OK I solved the problem by copying code from Makefile in the Caffe installation to Makefile for caffe-crfrnn. By 'code' I mean bits related to opencv. In addition to OPENCV_VERSION := 3 in Makefile.config I  added 

```
USE_OPENCV ?= 1

ifeq ($(USE_OPENCV), 1)
        LIBRARIES += opencv_core opencv_highgui opencv_imgproc

        ifeq ($(OPENCV_VERSION), 3)
                LIBRARIES += opencv_imgcodecs
        endif
endif

# OpenCV
ifeq ($(USE_OPENCV), 1)
        COMMON_FLAGS += -DUSE_OPENCV
endif
```

And it worked!

**Comment by bittnt** [comment]
Thanks @AlexTS1980 I have updated the code.
