### ISSUE TITLE
All backward will be zeros if "lr_mult" of Deconvolution layer is assigned as non-zero.

### ISSUE THREAD

**Issue by thesby** [torrvision/crfasrnn#54]
I used the crfasrnn to train a new model, and when "lr_mult" of Deconvolution layer is assigned as non-zero, for example, 1 or 10, then the backward of all layers are zeros. And the loss will quickly go down to 0.00138931. Why can not the lr_mult  be non-zero ? Thank you.

**Comment by bittnt** [comment]
I do not think it matters with "lr_mult".

As far as I know, for new prototxt, it might worthwhile to check if the weights for deconvolution layers are initialized properly. If you change the name of deconvolution layer, the weights might just initialize to zero. In new code base, you can set the weight initialization for deconvolution layer, but it does not exist in the previous code base.

**Comment by thesby** [comment]
@bittnt Thank you for your answer. I just want to train a new model without any restoring, and all the convolutional / deconvolutional parameters are initialized with xavier method. If "lr_mult" is non-zero, all the backward blobs become zeros. It seems strange.

**Comment by thesby** [comment]
@bittnt I am sorry that I have merged your caffe version to the latest caffe before your granting and published [CRFasRNN-merge](https://github.com/thesby/CRFasRNN-merge). If you are not satisfy with this, I will remove the repository as soon as possible.

**Comment by thesby** [comment]
I rebuild the caffe, and it works right now. I think there is some other error, not lr_mult.

**Comment by bittnt** [comment]
deconvolutional parameters should be initialized with bilinear weights. e.g.
```
layer {
  name: "upsample_example"
  type: "Deconvolution"
  bottom: "upscore2"
  top: "upscore4"
  param {
    lr_mult: 0
  }
        convolution_param{
                bias_term: false
                num_output: 21
                kernel_size: 4
                stride: 2
                pad: 1
                weight_filler: { type: "bilinear" }
        }
}
```

**Comment by bittnt** [comment]
It is great to hear that you successfully merged the code with caffe upstream. 

I have also done a version in crfrnn branch of our caffe fork.

**Comment by thesby** [comment]
Wow, bilinear should be better than xavier for expanding. I will try this. Thank you
