### ISSUE TITLE
Check failed: pFile The file 'spatial.par' is not found. Please create it with initial spatial kernel weights

### ISSUE THREAD

**Issue by AlexTS1980** [torrvision/crfasrnn#56]
This is really silly, but I couldn't solve it myself. 

Everything works fine when I run the demo script from the directory created when installing crfasrnn, but when I do it from elsewhere (with no other errors reported), I get this:

Check failed: pFile The file 'spatial.par' is not found. Please create it with initial spatial kernel weights

I followed the suggestion in https://github.com/torrvision/crfasrnn/issues/19, but it didn't work. I looked at 
multi_stage_meanfield.cpp, but I'm not too sure what to do. Once again, all is fine when I run it from crfasrnn-master/python-scripts/

Any suggesitons?

**Comment by bittnt** [comment]
Place those two files in your executed path.

**Comment by AlexTS1980** [comment]
I knew it was a silly question! thanks
