### ISSUE TITLE
Memory Requirements on CPU

### ISSUE THREAD

**Issue by eevolvelab** [torrvision/crfasrnn#58]
I am wondering how much RAM memory is required to segment 500x500 image? 

I am running the crfasrnn on EC2 instance CPU and seems like it is consuming around 6GB of RAM memory. Is that correct number or I am doing something wrong.

If that is true then is there a way to reduce the memory usage.

Also I found one of the Issues which is related to GPU on AWS EC2. Graphics EC2 instance on AWS has maximum of 4GB of video memory, and crfasrnn requires around 8GB of RAM memory. Is there any progress in reducing the memory usage.

Thank you in advance.

**Comment by bittnt** [comment]
Try https://github.com/BVLC/caffe/pull/2016 for the moment.

**Comment by eevolvelab** [comment]
@bittnt  Thank you for the pointer. 
After incorporating that change, I see the memory consumption reduces from approx. 7GB to nearly 5.71GB.
