### ISSUE TITLE
Where to get the model?

### ISSUE THREAD

**Issue by LiutongGenius** [torrvision/crfasrnn#64]
The command "sh download_trained_model.sh" says "failed: No route to host."
And I tried to get the model by directly clicking the link in python-scripts/README.md,but I get Error 404 which says "The requested URL /~szheng/Res_CRFRNN/TVG_CRFRNN_COCO_VOC.caffemodel was not found on this server. "

Is the url not used anymore? And where can I get the model?

**Comment by bittnt** [comment]
https://github.com/torrvision/crfasrnn/blob/master/python-scripts/download_trained_model.sh

**Comment by LiutongGenius** [comment]
I tried your suggestion just now,but I still failed to download the model,the command lines displays as below:

--2016-08-22 19:52:01--  http://goo.gl/j7PrPZ
Resolving goo.gl... 216.58.199.110, 2404:6800:4005:80a::200e
Connecting to goo.gl|216.58.199.110|:80... failed: Operation timed out.
Connecting to goo.gl|2404:6800:4005:80a::200e|:80... failed: No route to host.

**Comment by bittnt** [comment]
I guess you might not be able to use Google (https://goo.gl/) at all.

It should works fine outside of China as far as I know.
