### ISSUE TITLE
cannot solve: Cannot use GPU in CPU-only Caffe: check mode

### ISSUE THREAD

**Issue by sunle2009** [torrvision/crfasrnn#65]
Hi,

When I run: python crfasrnn_demo.py
The problem is as:
*********************************************
Input file is " input.jpg
Output file is " output.png
GPU_DEVICE is " 0
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0829 22:22:03.615937 22095 common.cpp:66] Cannot use GPU in CPU-only Caffe: check mode.
*** Check failure stack trace: ***
Aborted (core dumped)
***************************************************************
I have uncommented the CPU_ONLY = 1 in the 'Makefile.config'
          Changed CMakeLists.txt: caffe_option(CPU_ONLY  "Build Caffe without CUDA support" ON)
          changed solver_mode: CPU in .prototxt files
************************************************************************
However, the problem is still there.
Would anyone like to help please?
Thanks very much

**Comment by bittnt** [comment]
which version did you try? did you try the latest python code?

**Comment by sunle2009** [comment]
Hi Shuai,

Thanks for your reply.
In this demo script:
https://github.com/torrvision/crfasrnn/blob/master/python-scripts/crfasrnn_demo.py
why gpudevice >=0 ?

if gpudevice >=0:
#Do you have GPU device?
has_gpu = 1
#which gpu device is available?
gpu_device=gpudevice

**Comment by bittnt** [comment]
gpudevice=-1 means you do not have gpu device. If you have at least one GPU, you should be able to use gpudevice=0.

**Comment by sunle2009** [comment]
Hi
where is the examples/segmentationcrfasrnn please?
Cannot find it.
Thank you.

**Comment by sunle2009** [comment]
found it. Thank you.
