### ISSUE TITLE
CRF-RNN on Ubuntu 16.04

### ISSUE THREAD

**Issue by AlexTS1980** [torrvision/crfasrnn#68]
Does crf-rnn support cuda8? This is the only cuda compatible with Ubuntu 16.04. What version of CuDNN is supported on this platform?

**Comment by legel** [comment]
I'm about to embark on inspecting this, please report back if/when you discover; will do so likewise...

**Comment by AlexTS1980** [comment]
I'm using cuda 7.5 and cudnn 4. Caffe was installed correctly, but there's some cuda problem. crf-rnn has some problem with cudnn

**Comment by maloletnik** [comment]
I just installed cuda 8.0 and Caffe on aws p2 instance (Ubuntu 14.04). 
The crf-rnn demo in python runs ok.
I had to disable the cudnn (5.1) in order to build caffe.
