### ISSUE TITLE
Most of the test results are all black image.

### ISSUE THREAD

**Issue by ys404314023** [torrvision/crfasrnn#69]
hi . 
i train my data on gpu Iteration over 100 thousand times.
But the result is very bad.
Even a very result is just a full black image.

i can't solve this problem,i need you help , thank you!

**Comment by bittnt** [comment]
This problem often happens because the upsampling layer is not initialised with correct weights.

**Comment by Sam813** [comment]
@bittnt  may I know how should I initialize the weights? I have two class of foreground and background (organ segmentation)  
I have tried below for initialization of deconvolution layer:
layer {
  name: "score2-new"
  type: "Deconvolution"
  bottom: "score"
  top: "score2-new"
  param {
    lr_mult: 1
  }
  convolution_param {
    num_output: 2 #21
    kernel_size: 4
    stride: 2
    weight_filler: {  type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 0.2}

also once tried initialization with xavier method but in both case still all my predictions are in black.

**Comment by Sam813** [comment]
@bittnt thank you for fast response, 
I will try it and update everyone here, 
shall I do the same initialization for all deconvolution layers or just for upsample layer?

**Comment by Sam813** [comment]
@bittnt I have tried to train the network with bilinear initialization of deconv layers but yet the output
 is black. 
can you please take a quick look at the train prototxt to see if the setup s correct?
[new_prototxt.txt](https://github.com/torrvision/crfasrnn/files/2104801/new_prototxt.txt)

**Comment by bittnt** [comment]
I think you made several mistakes in that prototxt, e.g. you set the initialization for the convolution using bilinear.... This is wrong. You can take msra or something to initialize the convolution. please make sure you follow the examples, and you really read the caffe documentations about CNN layers. https://github.com/torrvision/caffe/blob/crfrnn/examples/crfasrnn_segmentation/TVG_CRFRNN_new_traintest.prototxt
