### ISSUE TITLE
supplementary material

### ISSUE THREAD

**Issue by chanmi** [torrvision/crfasrnn#74]
Hello.
In the paper section 5.2, 
you said 
"The complete architecture of our network, including the FCN-8s part can be found in the supplementary material."
But I can't find the supplementary material.
Could you let me know the link for that?
thank you.

**Comment by stoneyang** [comment]
Um, your quotation seems to be in Section 6. @chanmi 

Could you please pointing out the address of the supplementary material? @bittnt 

Cheers.

**Comment by bittnt** [comment]
@chanmi @stoneyang Thanks for pointing out this. The architecture is presented in this github repository. Please refer to the latest version of the paper:
http://www.robots.ox.ac.uk/~szheng/papers/CRFasRNN.pdf
Thanks.

**Comment by stoneyang** [comment]
@bittnt Thanks for your reminder! I've updated my copy of the paper.
