### ISSUE TITLE
Mean color value subtraction - in the test phase but not in the training phase

### ISSUE THREAD

**Issue by nastyad** [torrvision/crfasrnn#76]
Hello,

In the test phase, the mean vector [103.939, 116.779, 123.68] is subtracted from the image RGB values prior to the segmentation. Why in the train phase no mean values are computed or subtracted - at least not in `TVG_CRFRNN_new_traintest.prototxt`?

Thank you,
Anastasia

**Comment by bittnt** [comment]
You could do the Mean color value substraction either in prototxt or in the script you used to create lmdb.
