### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by wajahatamin** [torrvision/crfasrnn#83]
The demo is not working for me
gives runtime error on the following line of code
net = tvg_matcaffe_init(use_gpu, gpu_id, model_def_file, model_file);
**the logs on terminal are**

[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 626:25: Message type "caffe.MultiStageMeanfieldParameter" has no field named "spatial_filter_weight".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1123 12:23:38.740509  6596 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: TVG_CRFRNN_new_deploy.prototxt

**Stack Trace**

------------------------------------------------------------------------
              abort() detected at Tue Nov 22 15:36:43 2016
------------------------------------------------------------------------

Configuration:
  Crash Decoding     : Disabled
  Current Visual     : 0x21 (class 4, depth 24)
  Default Encoding   : UTF-8
  GNU C Library      : 2.19 stable
  MATLAB Architecture: glnxa64
  MATLAB Root        : /usr/local/MATLAB/R2014
  MATLAB Version     : 8.3.0.532 (R2014a)
  Operating System   : Linux 3.19.0-51-generic #58~14.04.1-Ubuntu SMP Fri Feb 26 22:02:58 UTC 2016 x86_64
  Processor ID       : x86 Family 6 Model 63 Stepping 2, GenuineIntel
  Virtual Machine    : Java 1.7.0_11-b21 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  Window System      : The X.Org Foundation (11701000), display :0

Fault Count: 1

Abnormal termination:
abort()

Register State (from fault):
  RAX = 0000000000000000  RBX = 00007f7604262620
  RCX = ffffffffffffffff  RDX = 0000000000000006
  RSP = 00007f76e0fc5df8  RBP = 00007f76e0fc5f30
  RSI = 00000000000052e0  RDI = 00000000000052b9

   R8 = 000000000000ff08   R9 = ffffffffffff1150
  R10 = 0000000000000008  R11 = 0000000000000202
  R12 = 0000000000000001  R13 = 00007f76e0fc6170
  R14 = 00007f76e0fc6b90  R15 = 0000000000000001

  RIP = 00007f76f339acc9  EFL = 0000000000000202

   CS = 0033   FS = 0000   GS = 0000

Stack Trace (from fault):
[  0] 0x00007f76f339acc9                    /lib/x86_64-linux-gnu/libc.so.6+00224457 gsignal+00000057
[  1] 0x00007f76f339e0d8                    /lib/x86_64-linux-gnu/libc.so.6+00237784 abort+00000328
[  2] 0x00007f760403cd81             /usr/lib/x86_64-linux-gnu/libglog.so.0+00068993 _ZN6google22InstallFailureFunctionEPFvvE+00000000
[  3] 0x00007f760403cdaa             /usr/lib/x86_64-linux-gnu/libglog.so.0+00069034 _ZN6google10LogMessage10SendToSinkEv+00000000
[  4] 0x00007f760403cce4             /usr/lib/x86_64-linux-gnu/libglog.so.0+00068836 _ZN6google10LogMessage9SendToLogEv+00001224
[  5] 0x00007f760403c6e6             /usr/lib/x86_64-linux-gnu/libglog.so.0+00067302 _ZN6google10LogMessage5FlushEv+00000414
[  6] 0x00007f760403f687             /usr/lib/x86_64-linux-gnu/libglog.so.0+00079495 _ZN6google15LogMessageFatalD1Ev+00000025
[  7] 0x00007f76045786de /home/tabazim/Downloads/caffe-master/matlab/+caffe/private/caffe_.mexa64+00747230
[  8] 0x00007f760466e693 /home/tabazim/Downloads/caffe-master/matlab/+caffe/private/caffe_.mexa64+01754771
[  9] 0x00007f76044fd8d3 /home/tabazim/Downloads/caffe-master/matlab/+caffe/private/caffe_.mexa64+00243923
[ 10] 0x00007f76044fe397 /home/tabazim/Downloads/caffe-master/matlab/+caffe/private/caffe_.mexa64+00246679 mexFunction+00000154
[ 11] 0x00007f76eb2c572a      /usr/local/MATLAB/R2014/bin/glnxa64/libmex.so+00120618 mexRunMexFile+00000090
[ 12] 0x00007f76eb2c1a94      /usr/local/MATLAB/R2014/bin/glnxa64/libmex.so+00105108
[ 13] 0x00007f76eb2c2fb4      /usr/local/MATLAB/R2014/bin/glnxa64/libmex.so+00110516
[ 14] 0x00007f76ea6bcad9 /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_dispatcher.so+00670425 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000697
[ 15] 0x00007f76e99592b4 /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+04461236
[ 16] 0x00007f76e995abc9 /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+04467657
[ 17] 0x00007f76e995b3fc /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+04469756
[ 18] 0x00007f76e97d56e3 /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02873059
[ 19] 0x00007f76e97e509e /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02936990
[ 20] 0x00007f76e97e5183 /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02937219
[ 21] 0x00007f76e991b172 /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+04206962
[ 22] 0x00007f76e9751df8 /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02334200
[ 23] 0x00007f76e97af30b /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02716427
[ 24] 0x00007f76ea6bcad9 /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_dispatcher.so+00670425 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000697
[ 25] 0x00007f76ea2f46e8   /usr/local/MATLAB/R2014/bin/glnxa64/libmwmcos.so+01566440
[ 26] 0x00007f76ea29e482   /usr/local/MATLAB/R2014/bin/glnxa64/libmwmcos.so+01213570
[ 27] 0x00007f76ea2a0465   /usr/local/MATLAB/R2014/bin/glnxa64/libmwmcos.so+01221733
[ 28] 0x00007f76ea2a2e50   /usr/local/MATLAB/R2014/bin/glnxa64/libmwmcos.so+01232464
[ 29] 0x00007f76ea2a073d   /usr/local/MATLAB/R2014/bin/glnxa64/libmwmcos.so+01222461
[ 30] 0x00007f76ea2f7126   /usr/local/MATLAB/R2014/bin/glnxa64/libmwmcos.so+01577254
[ 31] 0x00007f76ea36355b   /usr/local/MATLAB/R2014/bin/glnxa64/libmwmcos.so+02020699
[ 32] 0x00007f76ea66b874 /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_dispatcher.so+00338036 _ZN13Mfh_MATLAB_fn11dispatch_fhEiPP11mxArray_tagiS2_+00000244
[ 33] 0x00007f76ea363031   /usr/local/MATLAB/R2014/bin/glnxa64/libmwmcos.so+02019377
[ 34] 0x00007f76e979320e /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02601486
[ 35] 0x00007f76e974e1d0 /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02318800
[ 36] 0x00007f76e97501ea /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02327018
[ 37] 0x00007f76e9753167 /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02339175
[ 38] 0x00007f76e975126f /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02331247
[ 39] 0x00007f76e9751ec4 /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02334404
[ 40] 0x00007f76e97af30b /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02716427
[ 41] 0x00007f76ea6bcad9 /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_dispatcher.so+00670425 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000697
[ 42] 0x00007f76ea2f46e8   /usr/local/MATLAB/R2014/bin/glnxa64/libmwmcos.so+01566440
[ 43] 0x00007f76ea2f4995   /usr/local/MATLAB/R2014/bin/glnxa64/libmwmcos.so+01567125
[ 44] 0x00007f76ea29e236   /usr/local/MATLAB/R2014/bin/glnxa64/libmwmcos.so+01212982
[ 45] 0x00007f76ea29e98c   /usr/local/MATLAB/R2014/bin/glnxa64/libmwmcos.so+01214860
[ 46] 0x00007f76ea2a038e   /usr/local/MATLAB/R2014/bin/glnxa64/libmwmcos.so+01221518
[ 47] 0x00007f76ea2a2e50   /usr/local/MATLAB/R2014/bin/glnxa64/libmwmcos.so+01232464
[ 48] 0x00007f76ea2a0a9c   /usr/local/MATLAB/R2014/bin/glnxa64/libmwmcos.so+01223324
[ 49] 0x00007f76ea2a0be9   /usr/local/MATLAB/R2014/bin/glnxa64/libmwmcos.so+01223657
[ 50] 0x00007f76ea2a0dcf   /usr/local/MATLAB/R2014/bin/glnxa64/libmwmcos.so+01224143
[ 51] 0x00007f76ea2a0ff1   /usr/local/MATLAB/R2014/bin/glnxa64/libmwmcos.so+01224689
[ 52] 0x00007f76ea2fc717   /usr/local/MATLAB/R2014/bin/glnxa64/libmwmcos.so+01599255
[ 53] 0x00007f76ea3631f8   /usr/local/MATLAB/R2014/bin/glnxa64/libmwmcos.so+02019832
[ 54] 0x00007f76ea66b874 /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_dispatcher.so+00338036 _ZN13Mfh_MATLAB_fn11dispatch_fhEiPP11mxArray_tagiS2_+00000244
[ 55] 0x00007f76ea363031   /usr/local/MATLAB/R2014/bin/glnxa64/libmwmcos.so+02019377
[ 56] 0x00007f76e979320e /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02601486
[ 57] 0x00007f76e974e1d0 /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02318800
[ 58] 0x00007f76e97501ea /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02327018
[ 59] 0x00007f76e9753167 /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02339175
[ 60] 0x00007f76e975126f /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02331247
[ 61] 0x00007f76e9751ec4 /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02334404
[ 62] 0x00007f76e97af30b /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02716427
[ 63] 0x00007f76ea6bcad9 /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_dispatcher.so+00670425 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00000697
[ 64] 0x00007f76e979320e /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02601486
[ 65] 0x00007f76e97341b0 /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02212272
[ 66] 0x00007f76e974f25f /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02323039
[ 67] 0x00007f76e9753167 /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02339175
[ 68] 0x00007f76e975126f /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02331247
[ 69] 0x00007f76e9751ec4 /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02334404
[ 70] 0x00007f76e97af30b /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02716427
[ 71] 0x00007f76ea6bcc5f /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_dispatcher.so+00670815 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00001087
[ 72] 0x00007f76e979320e /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02601486
[ 73] 0x00007f76e97341b0 /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02212272
[ 74] 0x00007f76e974f25f /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02323039
[ 75] 0x00007f76e9753167 /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02339175
[ 76] 0x00007f76e975126f /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02331247
[ 77] 0x00007f76e9751ec4 /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02334404
[ 78] 0x00007f76e97af30b /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02716427
[ 79] 0x00007f76ea6bcc5f /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_dispatcher.so+00670815 _ZN8Mfh_file11dispatch_fhEiPP11mxArray_tagiS2_+00001087
[ 80] 0x00007f76e9782135 /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02531637
[ 81] 0x00007f76e97490d9 /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02298073
[ 82] 0x00007f76e9745dc7 /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02284999
[ 83] 0x00007f76e9746193 /usr/local/MATLAB/R2014/bin/glnxa64/libmwm_interpreter.so+02285971
[ 84] 0x00007f76eb4efafc /usr/local/MATLAB/R2014/bin/glnxa64/libmwbridge.so+00142076
[ 85] 0x00007f76eb4f0791 /usr/local/MATLAB/R2014/bin/glnxa64/libmwbridge.so+00145297 _Z8mnParserv+00000721
[ 86] 0x00007f76f449f92f    /usr/local/MATLAB/R2014/bin/glnxa64/libmwmcr.so+00489775 _ZN11mcrInstance30mnParser_on_interpreter_threadEv+00000031
[ 87] 0x00007f76f4480b6d    /usr/local/MATLAB/R2014/bin/glnxa64/libmwmcr.so+00363373
[ 88] 0x00007f76f4480be9    /usr/local/MATLAB/R2014/bin/glnxa64/libmwmcr.so+00363497
[ 89] 0x00007f76e8e7bd46    /usr/local/MATLAB/R2014/bin/glnxa64/libmwuix.so+00343366
[ 90] 0x00007f76e8e5e382    /usr/local/MATLAB/R2014/bin/glnxa64/libmwuix.so+00222082
[ 91] 0x00007f76f4bf550f /usr/local/MATLAB/R2014/bin/glnxa64/libmwservices.so+02323727
[ 92] 0x00007f76f4bf567c /usr/local/MATLAB/R2014/bin/glnxa64/libmwservices.so+02324092
[ 93] 0x00007f76f4bf157f /usr/local/MATLAB/R2014/bin/glnxa64/libmwservices.so+02307455
[ 94] 0x00007f76f4bf69b5 /usr/local/MATLAB/R2014/bin/glnxa64/libmwservices.so+02329013
[ 95] 0x00007f76f4bf6de7 /usr/local/MATLAB/R2014/bin/glnxa64/libmwservices.so+02330087
[ 96] 0x00007f76f4bf74c0 /usr/local/MATLAB/R2014/bin/glnxa64/libmwservices.so+02331840 _Z25svWS_ProcessPendingEventsiib+00000080
[ 97] 0x00007f76f4481098    /usr/local/MATLAB/R2014/bin/glnxa64/libmwmcr.so+00364696
[ 98] 0x00007f76f44813bf    /usr/local/MATLAB/R2014/bin/glnxa64/libmwmcr.so+00365503
[ 99] 0x00007f76f447c28f    /usr/local/MATLAB/R2014/bin/glnxa64/libmwmcr.so+00344719
[100] 0x00007f76f3731182              /lib/x86_64-linux-gnu/libpthread.so.0+00033154
[101] 0x00007f76f345e47d                    /lib/x86_64-linux-gnu/libc.so.6+01025149 clone+00000109

This error was detected while a MEX-file was running. If the MEX-file
is not an official MathWorks function, please examine its source code
for errors. Please consult the External Interfaces Guide for information
on debugging MEX-files.

**Comment by bittnt** [comment]
This error message suggests you are using the new version of caffe-crfasrnn, you should change the prototxt. There are two parameters in multistagemeanfield, spatial_filter_weight_str, and bilateral_filter_weight_str. spatial_filter_weight and bilateral_filter_weight should be removed if you are using the new version of caffe-crfasrnn.

**Comment by dachengxiaocheng** [comment]
@bittnt Hi Shuai:
If I want to use the new crf-rnn version, what should I do with the prototxt file? I just delete the parameters "spatial_filter_weight: 3" and "bilateral_filter_weight: 5". But there are new errors 
" solver = caffe.SGDSolver('solver.prototxt') 
RuntimeError: A malformed string! ><. Couldn't read 23 values."
Thanks for your help!

**Comment by bittnt** [comment]
layer {
name: "inference1"
type: "MultiStageMeanfield"
bottom: "unary"
bottom: "Q0"
bottom: "data"
top: "score_post"
param {
lr_mult: 1000
}
param {
lr_mult: 1000
}
param {
lr_mult: 1000
}
multi_stage_meanfield_param {
spatial_filter_weights_str: "3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3"
bilateral_filter_weights_str: "5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5"
num_iterations: 5
compatibility_mode: POTTS
threshold: 2
theta_alpha: 59
theta_beta: 3
theta_gamma: 3
}
}
