### ISSUE TITLE
Error when compiling and running python demo

### ISSUE THREAD

**Issue by yc67** [torrvision/crfasrnn#85]
Hi, I compiled everything correctly and didn't have any error before this, but as I run the python demo, I received the following error. I didn't find anything like it on Google also. May I get some suggestion? Thanks!
<img width="986" alt="2016-11-26 9 00 01" src="https://cloud.githubusercontent.com/assets/23995909/20645186/75c45554-b41b-11e6-87c0-c5a30aa0940f.png">

**Comment by bittnt** [comment]
Let me know if you still have problems if you compile the caffe-crfasrnn (https://github.com/bittnt/caffe) source code and its python interface. 
You need to first set up the path in Makefile.config, and make sure you have done: "make" and then "make python".
Make sure you add the path of the caffe-crfasrnn into the python package path.

**Comment by yc67** [comment]
Thanks it works! I was running a different caffe installation. Recompiling makes it work.
