### ISSUE TITLE
caffe.MultiStageMeanfieldParameter" has no field named "spatial_filter_weight

### ISSUE THREAD

**Issue by zhuihunmiling** [torrvision/crfasrnn#88]
`/usr/bin/python2.7 /home/simon/Desktop/crfasrnn-master/python-scripts/crfasrnn_demo.py
Input file is " input.jpg
Output file is " output.png
GPU_DEVICE is " 0
WARNING: Logging before InitGoogleLogging() is written to STDERR
W1207 23:30:13.552337 16866 _caffe.cpp:122] DEPRECATION WARNING - deprecated use of Python interface
W1207 23:30:13.552371 16866 _caffe.cpp:123] Use this instead (with the named "weights" parameter):
W1207 23:30:13.552376 16866 _caffe.cpp:125] Net('TVG_CRFRNN_new_deploy.prototxt', 1, weights='TVG_CRFRNN_COCO_VOC.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 626:25: Message type "caffe.MultiStageMeanfieldParameter" has no field named "spatial_filter_weight".
F1207 23:30:13.554874 16866 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: TVG_CRFRNN_new_deploy.prototxt
*** Check failure stack trace: ***`

my caffe version is https://github.com/bittnt/caffe/tree/crfrnn
who can help me, thanks!

**Comment by dachengxiaocheng** [comment]
Hi all

I encountered the same problem. My error is below:

I1212 18:26:29.364348 32582 solver.cpp:91] Creating training net from net file: CRFRNN_train_test_GPU.prototxt
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 699:25: Message type "caffe.MultiStageMeanfieldParameter" has no field named "spatial_filter_weight".

F1212 18:26:29.365051 32582 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: CRFRNN_train_test_GPU.prototxt

*** Check failure stack trace: ***
Aborted (core dumped)

Any ideas about this? 

Many thanks for your help!

**Comment by bittnt** [comment]
layer {
  name: "inference1"
  type: "MultiStageMeanfield"
  bottom: "unary"
  bottom: "Q0"
  bottom: "data"
  top: "score_post"
  param {
    lr_mult: 1000
  }
  param {
    lr_mult: 1000
  }
  param {
   lr_mult: 1000
  }
  multi_stage_meanfield_param {
    spatial_filter_weights_str: "3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3"
    bilateral_filter_weights_str: "5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5"
    num_iterations: 5
    compatibility_mode: POTTS
    threshold: 2
    theta_alpha: 59
    theta_beta: 3
    theta_gamma: 3
   }
}

**Comment by dachengxiaocheng** [comment]
@bittnt Hi Shuai
Thanks so much for your help. Now I use the new parameters spatial_filter_weights_str: "3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3" and bilateral_filter_weights_str: "5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5" in prototxt.

But a new error appears:
I1213 13:27:29.764771 19172 multi_stage_meanfield.cpp:56] This implementation has not been tested batch size > 1.
Traceback (most recent call last):
  File "solve.py", line 17, in <module>
    solver = caffe.SGDSolver('solver.prototxt')
RuntimeError: A malformed string! >3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3<. Couldn't read 23 values.

**Comment by dachengxiaocheng** [comment]
@bittnt Hi

Sorry, it is a silly error. I had fixed it. Cheers

**Comment by zhuihunmiling** [comment]
@bittnt Thanks a lot for your help. Now, it works!

**Comment by wk910930** [comment]
Hi @dachengxiaocheng , I met the similar error `A malformed string! >3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3<. Couldn't read 84 values`. How did you fix it? Thanks.

**Comment by qincao1994** [comment]
@dachengxiaocheng 
hello, I encounter the same problem. Could you help me?
Traceback (most recent call last):
File "solve.py", line 41, in <module>
solver = caffe.SGDSolver('solver.prototxt')
RuntimeError: A malformed string! ><. Couldn't read 41 values.
