### ISSUE TITLE
Getting tags of the segments

### ISSUE THREAD

**Issue by skeeph** [torrvision/crfasrnn#9]
Hello. I compiled this code and successfully ran demo. But I have question. For arbitary images, how can I get tags of segment?

**Comment by bittnt** [comment]
@skeeph 
You can recover the tag of segment (object class) by using the colour encode.

In python script, you should get a understanding about this from:
pallete = [0,0,0,
            128,0,0,
            0,128,0,
            128,128,0,
            0,0,128,
            128,0,128,
            0,128,128,
            128,128,128,
            64,0,0,
            192,0,0,
            64,128,0,
            192,128,0,
            64,0,128,
            192,0,128,
            64,128,128,
            192,128,128,
            0,64,0,
            128,64,0,
            0,192,0,
            128,192,0,
            0,64,128,
            128,64,128,
            0,192,128,
            128,192,128,
            64,64,0,
            192,64,0,
            64,192,0,
            192,192,0]
Each row represents one class. For example, [0, 0, 0] means background. [128,0,0] indicates aeroplane. I hope you could figure it out.

**Comment by skeeph** [comment]
OK, thanks.
